services:
  server:
    build:
      context: .
    ports:
      - 4321:80
    volumes:
      - ./framework:/var/www/html
    networks:
      - app-network
    depends_on:
      - postgres
    entrypoint: sh -c "cd /var/www/html && composer update --no-interaction --prefer-dist && /usr/sbin/apache2ctl -D FOREGROUND"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - 54321:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: