services:
  server:
    build:
      context: .
    ports:
      - 4321:80
    volumes:
      - ./framework:/var/www/html
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - 54321:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: